[package]
name = "directio"
version = "0.1.4"
authors = ["rigma <rigbuntu@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
cfg-if = "0.1.10"
libc = "0.2.66"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winbase"] }
